### ISSUE TITLE
你好我想问下浏览数量和评论是需要自己实现吗

### ISSUE THREAD

**Issue by sutinghui24** [recoluan/vuepress-theme-reco#15]

**Comment by sutinghui24** [comment]
在评论组件和浏览数量没看到相关的逻辑，这个是需要自己实现还是有其他机制实现的

**Comment by goozyshi** [comment]
```  
themeConfig: {
    author: 'goozyshi',
    nav: NavConfig,
    // 评论设置
    valineConfig: {
      appId: '',// your appId
      appKey: '', // your appKey
    },
    // 最近一次更新
    lastUpdated: 'Last Updated',
  },
```
具体的appid和key去[LeanCloud](https://leancloud.cn/)

**Comment by sutinghui24** [comment]
<template>
  <span v-if="$site.themeConfig.valineConfig" :id="idVal" class="leancloud-visitors" data-flag-title="Your Article Title">
    <i class="iconfont reco-eye" style="margin-right: .5rem"></i>
    <a class="leancloud-visitors-count" :style="numStyle"></a>
  </span>
</template>

<script>
export default {
  props: ['idVal', 'numStyle']
}
</script>

<style lang="stylus" scoped>
.leancloud-visitors
  margin-right .5rem
</style>

**Comment by sutinghui24** [comment]
<template>
  <span v-if="$site.themeConfig.valineConfig" :id="idVal" class="leancloud-visitors" data-flag-title="Your Article Title">
    <i class="iconfont reco-eye" style="margin-right: .5rem"></i>
    <a class="leancloud-visitors-count" :style="numStyle"></a>
  </span>
</template>

<script>
export default {
  props: ['idVal', 'numStyle']
}
</script>

<style lang="stylus" scoped>
.leancloud-visitors
  margin-right .5rem
</style>

**Comment by sutinghui24** [comment]
真的没有你在评论组件创建了一个AV对象后就没用过相关的云存储的api了

**Comment by sutinghui24** [comment]
用你的主题是出来了

**Comment by recoluan** [comment]
**你好，请移步valine官网查看详细说明：**
- 评论功能的实现：https://valine.js.org/quickstart.html#npm
- 浏览统计的实现：https://valine.js.org/visitor.html

**Comment by lz1998** [comment]
valine是不是必须使用LeanCloud，如果保密数据不想放在LeanCloud，能否自己进行部署
