### ISSUE TITLE
没有评论和浏览量的页面也请求了 api

### ISSUE THREAD

**Issue by bougieL** [recoluan/vuepress-theme-reco#17]
每个页面都请求了 `leanCloud` ，即使这个页面没有评论框

**Comment by recoluan** [comment]
你好，这是我的另一个博客，没有弄评论功能，并没有请求啊，能把你的 `config.js` 的配置信息发一下吗？
<img width="1415" alt="comment" src="https://user-images.githubusercontent.com/18067907/55684517-1b488680-597e-11e9-8ecd-536532e77274.png">

**Comment by recoluan** [comment]
> 每个页面都请求了 `leanCloud` ，即使这个页面没有评论框

我发现我理解的不对，是在添加了评论功能的基础上，没有评论框的页面也会发送请求，是这个意思对吧，我已经记下了，在下次更新的时候修复，更新后我会来这里通知你的，感谢你的宝贵意见。

**Comment by bougieL** [comment]
加油！https://www.bougieblog.cn/, 我最近把自己的博客改成了 vuepress ，但是 build 后文章列表内容没有直接输出到 html 中，想和你交流一下来着 :grinning:。

**Comment by recoluan** [comment]
可以啊，你可以加我微信，我的微信在我的博客里有，就不在这里贴了。

**Comment by recoluan** [comment]
我尝试在不需要添加评论的页面禁止valie组件的加载，但是发现这样是不行的，因为，会影响到某些页面的浏览统计，所以为了兼容性，暂时可行的解决办法，不好意思，如果你发现好的解决办法，可以交流。

所以我暂时先把这个问题关闭了。
