### ISSUE TITLE
Category、Tag不能修改成汉字

### ISSUE THREAD

**Issue by skywalker1992** [recoluan/vuepress-theme-reco#21]
当我注释调 text: 'Tag' 后
![image](https://user-images.githubusercontent.com/17719359/56339794-3ae37880-61e2-11e9-9a42-b64914313720.png)
打开页面正常，但是如果我点击一下首页或者Category或者标签，就出现了bug:
![image](https://user-images.githubusercontent.com/17719359/56339891-a2012d00-61e2-11e9-9095-58d9c1e0dce1.png)

**Comment by recoluan** [comment]
收到，感谢你的反馈，我会在下个版本中修复这个bug，并且会在这里提醒你。

**Comment by cchenggit** [comment]
同样遇到这个 bug, 只要点击Nav 就会出现重复的 nav
Console log报错:
```
Vue warn]: Duplicate keys detected: '/tag/'. This may cause an update error.

found in

---> <NavLinks> at node_modules/vuepress-theme-reco/components/NavLinks.vue
       <Sidebar> at node_modules/vuepress-theme-reco/components/Sidebar.vue
         <Common> at node_modules/vuepress-theme-reco/components/Common.vue
           <Category> at node_modules/vuepress-theme-reco/layouts/Category.vue
             <GlobalLayout> at node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue
               <Root>
```

**Comment by recoluan** [comment]
@skywalker1992 @cchenggit 问题已经在 `vuepress-theme-reco@1.0.0-alpha.15` 版本中修复，请跟新版本。

**Comment by cchenggit** [comment]
@recoluan 是我操作有问题还是没有更新?
我去 npm 上查询, 确实有1.0.0-alpha.15版本..
```
yarn global add vuepress-theme-reco@1.0.0-alpha.15
yarn global v1.15.2
warning package.json: No license field
[1/4] 🔍  Resolving packages...
Couldn't find any versions for "vuepress-theme-reco" that matches "1.0.0-alpha.15"
? Please choose a version of "vuepress-theme-reco" from this list:
❯ 1.0.0-alpha.12
  1.0.0-alpha.11
  1.0.0-alpha.10
  1.0.0-alpha.9
  1.0.0-alpha.8
  1.0.0-alpha.7
  1.0.0-alpha.6
  1.0.0-alpha.5
  1.0.0-alpha.4
  1.0.0-alpha.3
  1.0.0-alpha.2
  1.0.0-alpha.1
  0.3.11
  0.3.10
  0.3.9
  0.2.1
  0.2.0
  0.1.1
  0.1.0
  0.0.4
  0.0.3
  0.0.2
  0.0.1
```

**Comment by recoluan** [comment]
> @recoluan 是我操作有问题还是没有更新?
> 我去 npm 上查询, 确实有1.0.0-alpha.15版本..
> 
> ```
> yarn global add vuepress-theme-reco@1.0.0-alpha.15
> yarn global v1.15.2
> warning package.json: No license field
> [1/4] 🔍  Resolving packages...
> Couldn't find any versions for "vuepress-theme-reco" that matches "1.0.0-alpha.15"
> ? Please choose a version of "vuepress-theme-reco" from this list:
> ❯ 1.0.0-alpha.12
>   1.0.0-alpha.11
>   1.0.0-alpha.10
>   1.0.0-alpha.9
>   1.0.0-alpha.8
>   1.0.0-alpha.7
>   1.0.0-alpha.6
>   1.0.0-alpha.5
>   1.0.0-alpha.4
>   1.0.0-alpha.3
>   1.0.0-alpha.2
>   1.0.0-alpha.1
>   0.3.11
>   0.3.10
>   0.3.9
>   0.2.1
>   0.2.0
>   0.1.1
>   0.1.0
>   0.0.4
>   0.0.3
>   0.0.2
>   0.0.1
> ```

你好，我刚才试着也有这个问题，我又发布了一版，现在测试着没问题了。可能是因为刚才我在发布 `1.0.0-alpha.15` 版本的时候网不好，很长时间才发布上去，中间也许因为这个出现一些捕捉不到的问题。

> 刚开始我没有发现这个问题是因为，我在测试的时候，是直接修改 `package.json` 里的依赖的版本号，这样确实能下载下来，目前我也不清楚为什么直接用命令行下载会出问题，如果你以后找到了原因，请告诉我。

**Comment by cchenggit** [comment]
@recoluan 可能是我用的淘宝的镜像问题, 切换成原本的就可以了.

**Comment by recoluan** [comment]
> @recoluan 可能是我用的淘宝的镜像问题, 切换成原本的就可以了.

不知道为什么，我这现在都不行了，我这两天关注一下这个问题，找找原因
