### ISSUE TITLE
文章页有点窄，与左侧TOC离得有点远。

### ISSUE THREAD

**Issue by handbye** [recoluan/vuepress-theme-reco#22]
如题，建议将文章页宽一点。

**Comment by recoluan** [comment]
好的，后期会考虑一下的

**Comment by dongdawang** [comment]
你这个里左侧TOC又变的好近，我找不到在哪里调的参数了

**Comment by recoluan** [comment]
> 你这个里左侧TOC又变的好近，我找不到在哪里调的参数了

请注名你的 `vuepress` 版本和 `vuepress-theme-reco` 的版本，并提供一下截图。

**Comment by dongdawang** [comment]
![image](https://user-images.githubusercontent.com/18241524/59919269-94be2400-9459-11e9-8a0e-2359583da3fe.png)
就是这个问题，我在chrome使用F12手动把content default改成content_default就可以了，但是在源码里我不知道怎么改。

**Comment by recoluan** [comment]
> ![image](https://user-images.githubusercontent.com/18241524/59919269-94be2400-9459-11e9-8a0e-2359583da3fe.png)
> 就是这个问题，我在chrome使用F12手动把content default改成content_default就可以了，但是在源码里我不知道怎么改。

这个问题，我已经在 `1.0.0-alpha.23` 版本中解决这个问题了，你只要更新到 `1.0.0-alpha.23` 及以上的版本就可以了。

**Comment by dongdawang** [comment]
![image](https://user-images.githubusercontent.com/18241524/59931275-33a54900-9477-11e9-98af-5c1b23184cb9.png)
已经更新到这个版本了。
![image](https://user-images.githubusercontent.com/18241524/59931348-5afc1600-9477-11e9-8270-fa5132733340.png)

**Comment by recoluan** [comment]
> ![image](https://user-images.githubusercontent.com/18241524/59931275-33a54900-9477-11e9-98af-5c1b23184cb9.png)
> 已经更新到这个版本了。
> ![image](https://user-images.githubusercontent.com/18241524/59931348-5afc1600-9477-11e9-8270-fa5132733340.png)

那你将项目发到我的邮箱吧，我看一下：luanhewei@gmail.com
