### ISSUE TITLE
首页页脚可以自定义

### ISSUE THREAD

**Issue by aferica** [recoluan/vuepress-theme-reco#23]
##  首页页脚支持自定义，比如添加备案信息

在国内搭建自己的博客，备案几乎是避不开的，所以首页页脚不能修改有点尴尬
![image](https://user-images.githubusercontent.com/23699343/56704946-a7f69100-6741-11e9-826a-65e8d25fdc6d.png)

**Comment by recoluan** [comment]
好的，谢谢你的建议，我会在下个版本添加支持自定义页脚。

目前可以先在首页的内容区域编辑备案信息来显示。

**Comment by recoluan** [comment]
目前已经支持备案信息的自定义，请移步[文档](https://vuepress-theme-reco.recoluan.com/views/1.x/configJs.html#%E5%A4%87%E6%A1%88%E4%BF%A1%E6%81%AF%E5%92%8C%E9%A1%B9%E7%9B%AE%E5%BC%80%E5%A7%8B%E6%97%B6%E9%97%B4)。
