### ISSUE TITLE
请问markdown-it-plantuml 怎么不生效啊

### ISSUE THREAD

**Issue by liuzedong** [recoluan/vuepress-theme-reco#24]
![2019-05-18 20-57-28屏幕截图](https://user-images.githubusercontent.com/13012417/57970227-732cd100-79b1-11e9-882b-abff32f8c14b.png)
![2019-05-18 20-59-22屏幕截图](https://user-images.githubusercontent.com/13012417/57970215-47a9e680-79b1-11e9-8314-336458f8ceed.png)
![2019-05-18 20-59-35屏幕截图](https://user-images.githubusercontent.com/13012417/57970216-47a9e680-79b1-11e9-9cb5-4a5c228e875c.png)
![2019-05-18 20-59-55屏幕截图](https://user-images.githubusercontent.com/13012417/57970217-48427d00-79b1-11e9-8eff-3de76aff6ab5.png)

**Comment by recoluan** [comment]
感谢你的问题，我去解决一下，解决结果在这里通知你的。

**Comment by liuzedong** [comment]
谢谢， 还有一个问题， 我编译后放在github page上是好使的， 但是放在gitee page就排版都乱了

**Comment by recoluan** [comment]
> gitee page

贴一下你的 gitee page 链接

**Comment by liuzedong** [comment]
http://liuzedong.gitee.io/node/

**Comment by recoluan** [comment]
> 谢谢， 还有一个问题， 我编译后放在github page上是好使的， 但是放在gitee page就排版都乱了

这是因为你的 gitee page 不在根域名下，所以你需要在 `config.js` 中设置 `base: '/node/'`。

**Comment by liuzedong** [comment]
好的， 谢谢

**Comment by recoluan** [comment]
> 谢谢， 还有一个问题， 我编译后放在github page上是好使的， 但是放在gitee page就排版都乱了

你好，我尝试 `markdown-it-plantuml` 这个插件了，是不生效的，然后我尝试在默认主题使用也是不生效的，说明应该不是我的主题的问题。

我原来尝试使用过 `markdown-it-plugin-mermaid` 这个插件，也是不生效的。

目前我还找不到原因，我会继续关注这个问题的。

**Comment by liuzedong** [comment]
好的， 谢谢。麻烦你了

**Comment by recoluan** [comment]
> 好的， 谢谢。麻烦你了

今天我在看官方文档时候，发现你少写了一行代码，我加上以后可以正常运行了，你试一下。

<img width="374" alt="WX20190523-113544@2x" src="https://user-images.githubusercontent.com/18067907/58224115-ee460c80-7d4e-11e9-87f9-c335ad837acc.png">

**Comment by liuzedong** [comment]
![2019-05-23 14-07-09屏幕截图](https://user-images.githubusercontent.com/13012417/58229563-a7631180-7d64-11e9-93b3-65e958856cd5.png)

官方上面的，可以不写啊。

我自己也加上过，也是没有反应的

![2019-05-23 14-12-24屏幕截图](https://user-images.githubusercontent.com/13012417/58229642-d4afbf80-7d64-11e9-9c75-9e3a90c664af.png)

页面上
![2019-05-23 14-13-14屏幕截图](https://user-images.githubusercontent.com/13012417/58229694-f7da6f00-7d64-11e9-9a0d-a432e232f552.png)

**Comment by recoluan** [comment]
你是不是版本不对啊，你的 vuepress 是 0.x 还是 1.x？你发给我的文档截图是 0.x 的，你确认一下。我试过了，两个版本都没问题的，但是语法不一样。
![WX20190523-142132](https://user-images.githubusercontent.com/18067907/58230453-f14cf700-7d66-11e9-9b5d-635e177e6415.png)

**Comment by liuzedong** [comment]
![2019-05-23 14-38-14屏幕截图](https://user-images.githubusercontent.com/13012417/58231012-7ab0f900-7d68-11e9-91c6-3c6cdabf52f8.png)
vuepress 用的是1.0.0-alpha.47，  我是使用您的提供的cli  生成的项目

**Comment by recoluan** [comment]
那生成博客时选择的一定是 1.x，所以你需要看 1.x 的文档：[点击](https://v1.vuepress.vuejs.org/zh/)

**Comment by liuzedong** [comment]
好的， 谢谢， 是我看错文档
