### ISSUE TITLE
一级菜单不是链接

### ISSUE THREAD

**Issue by woytu** [recoluan/vuepress-theme-reco#25]
不知道这边主题是否可以解决？https://github.com/vuejs/vuepress/issues/1615

**Comment by recoluan** [comment]
你是想做成 a链接吗？这边主题是无法解决这个问题的，处理方式和默认主题保持一致。

请问你你要做成a链接的使用场景是什么样？

**Comment by woytu** [comment]
是的，我想做成a链接，因为我的一级菜单是一个文件夹，当点击一级菜单时默认跳转到这个文件夹下

**Comment by recoluan** [comment]
因为你这个需求比较特殊，所以不适合放在主题里，建议你为自己的项目自定义主题更合适。

**Comment by woytu** [comment]
也不是吧，每个文件夹默认不是有个README.md文件吗

**Comment by recoluan** [comment]
> 也不是吧，每个文件夹默认不是有个README.md文件吗

是有的，但是个人认为这个功能是不符合大众需求的，所以没办法在一个公用项目上增加这个功能，建议你自定义主题。

**Comment by woytu** [comment]
好的，谢谢
