### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by Mrzhoulichao** [recoluan/vuepress-theme-reco#27]
1. 图片如何引入？
2. 图片放在哪个目录才会被编译出来
3. 我在webpack =》 configureWebpack配置引入图片的别名是无效的。 
4. 我在 .vuepress 编写的 `.vuepress/override.styl` 文件无法生效

**Comment by recoluan** [comment]
1. 你说的图片是指文章里的图片吗？文章里的图片没有什么限制啊，只要放在 `.vuepress` 所在文件夹的地方就可以啊，我一般放在文章所在目录，这是我引入图片的方式： `![home.png](../images/home-blog.png)`；
2. `vuepress@1.x` 的 `override.styl` 更名为 `palette.styl`，它的目录更改为 `/.vuepress/styles/palette.styl`；
3. `configureWebpack` 的问题，建议你再检查一下你的语法是否正确，这是 `vuepress` 的功能，应该不会有问题的。

**Comment by Mrzhoulichao** [comment]
thk u

**Comment by microJ** [comment]
@llorz-o 关于 alias 问题我也发现了，在 #238 有解决。
