### ISSUE TITLE
【使用问题】bgImage 背景图片的min-height能否自定义？

### ISSUE THREAD

**Issue by liuliliGithub** [recoluan/vuepress-theme-reco#28]
## Feature request
你好，bgImage的min-height 能否自己设置？350px,我们认为太小，我们想自定义为850px

**Comment by recoluan** [comment]
> ## Feature request
> 你好，bgImage的min-height 能否自己设置？350px,我们认为太小，我们想自定义为850px

好的没问题，下一个版本会加入动态配置。

还有首页右侧的个人信息那里，都需要展示哪些信息，你也可以多提一下建议。

**Comment by liuliliGithub** [comment]
太好了。那我就不客气了：
- 个人信息哪里的分类和tag标签没有链接
- 博客文章的统计数是不是可以默认提供

**Comment by recoluan** [comment]
博客文章统计数默认提供不太现实：
1. 因为这个统计和评论功能都是由 `valine` 提供的，所以如果默认提供，也就是给所有用户提供一个一样的密钥，这本身属于用户自己私有的东西，这个不太好做成公有的；
2. 并且做成公有的，`valine` 的密钥会泄漏而无法控制，浪费资源。

如果你有好的解决方案，可以讨论去尝试一下。

**Comment by liuliliGithub** [comment]
也没有啥好办法。sorry，没帮到忙

**Comment by recoluan** [comment]
> 也没有啥好办法。sorry，没帮到忙

主题已经更新到 `1.0.1` 版本，首页可以自定义图片显示高度，个人信息栏新增了分类和标签等显示信息，具体看一下我的 [个人博客](https://www.recoluan.com) 吧。
