### ISSUE TITLE
网页打包后出现页面不跳转、组件缺失

### ISSUE THREAD

**Issue by yanyongyu** [recoluan/vuepress-theme-reco#30]
- [x] I confirm that this is an issue rather than a question.

#### What is actually happening?

npm run dev后预览的网页一切正常但是build之后的网页nginx加载浏览发现缺失了footer并且所有链接点击之后路由跳转了但页面并未变化。

#### Other relevant information

- Your OS: Windows10 1809
- Node.js version: 10.15.3
- VuePress version: 3.9.2
- VuePress-theme-reco version: 1.0.0-alpha.25
- Which package manager did you use for the install(npm/cnpm/yarn)? npm

**Comment by recoluan** [comment]
你好，你把主题版本号升级到 1.0.2，删除 node_modules 重新安装依赖再试一下。

**Comment by yanyongyu** [comment]
好的。这个奇奇怪怪的问题是个随机事件有时候再build一下又好了:joy:

**Comment by recoluan** [comment]
应该是不太稳定

CodeCreator <notifications@github.com> 于2019年7月18日周四 下午1:59写道：

**Comment by yanyongyu** [comment]
重新安装过了，版本也升级过了还是会出现。多build几次才能正常:joy:不知道问题在哪里

网址是[yyy.cs181.com.cn](yyy.cs181.com.cn)。

**Comment by recoluan** [comment]
博客很棒。

目前我没办法复现你的这个bug，并且还没有朋友反馈过这个问题😂，我会留意这个问题的。

**Comment by yanyongyu** [comment]
大佬可以看看我的历次commit
没记错的话这个deploy是有问题的-》[GitHub](https://github.com/yanyongyu/yanyongyu-blog/tree/fe352f31171b815b78a42e7ad21bef588fcccc6d/docs)

**Comment by recoluan** [comment]
朋友，现在怎么样了，我这里还是复现不了这个问题

**Comment by yanyongyu** [comment]
我每次都要build几次才能出现一个正常的:joy:，不过问题不大

**Comment by Xuminhua** [comment]
我在Mac上和Windows上感觉体验不太一样，也不知道哪里不一样

**Comment by recoluan** [comment]
> 我在Mac上和Windows上感觉体验不太一样，也不知道哪里不一样

你觉得是开发体验还是用户体验？
