### ISSUE TITLE
设置主题的色盘的颜色是否可以根据主题颜色一起变化？

### ISSUE THREAD

**Issue by Xuminhua** [recoluan/vuepress-theme-reco#31]
## Feature request
主题icon颜色根据主题选择变化

#### What problem does this feature solve?
更加直观的感觉到主题的切换

#### How should this be implemented in your opinion?
需要配置对应的icon的颜色

**Comment by recoluan** [comment]
好的，建议已收到，我在我的另一个项目中也发现了此问题，我会尝试去调整一下的。

**Comment by recoluan** [comment]
你的建议已经在 `1.0.4` 版本中得到体现，请及时升级。

**Comment by Xuminhua** [comment]
谢谢，非常棒

**Comment by Xuminhua** [comment]
改完有一个地方，就是导航栏里的文字，在inactive的时候页变成主题颜色了，之前的是只有active的标签有颜色。

**Comment by recoluan** [comment]
麻烦你再详细描述一下问题，或者截图将问题标记好

**Comment by Xuminhua** [comment]
修改后的导航栏里的文字  tag <a> 的都带上了主题颜色
![1](https://user-images.githubusercontent.com/10073763/62593201-77112500-b908-11e9-9805-3dffd216e51a.PNG)

是不是应该像下图这样，只有选中的页面才变色比较好？
![2](https://user-images.githubusercontent.com/10073763/62593208-7b3d4280-b908-11e9-81d5-61965d1d4bcc.PNG)

**Comment by recoluan** [comment]
> 修改后的导航栏里的文字 tag a 的都带上了主题颜色
> ![1](https://user-images.githubusercontent.com/10073763/62593201-77112500-b908-11e9-9805-3dffd216e51a.PNG)
> 
> 是不是应该像下图这样，只有选中的页面才变色比较好？
> ![2](https://user-images.githubusercontent.com/10073763/62593208-7b3d4280-b908-11e9-81d5-61965d1d4bcc.PNG)

我用的最新的主体，但是没出现这个问题，你能把修改后的代码提交一下吗？或者额截图贴在这
