### ISSUE TITLE
如何让博客增加GitHub Flavored Markdown语法?

### ISSUE THREAD

**Issue by LdFelix** [recoluan/vuepress-theme-reco#32]
#### What problem does this feature solve?
我使用了Typora来编写markdown文件,而文件中的高亮代码==和mermaid 代码都没法通过解释,都是原来的代码,这个问题是应该找vuepress吗?

**Comment by recoluan** [comment]
首先，vuepress是借助 `markdown-it` 来实现 markdown 的解析的，实现特殊的语法，可以借助插件，具体请点击 [这里](https://v1.vuepress.vuejs.org/zh/guide/markdown.html#%E8%BF%9B%E9%98%B6%E9%85%8D%E7%BD%AE)。

其次，我个人尝试过 `mermaid` 语法的插件，实际不太理想，可以使用 [vuepress-plugin-flowchart](https://flowchart.vuepress.ulivz.com/) 代替。

**Comment by LdFelix** [comment]
> 首先，vuepress是借助 `markdown-it` 来实现 markdown 的解析的，实现特殊的语法，可以借助插件，具体请点击 [这里](https://v1.vuepress.vuejs.org/zh/guide/markdown.html#%E8%BF%9B%E9%98%B6%E9%85%8D%E7%BD%AE)。
> 
> 其次，我个人尝试过 `mermaid` 语法的插件，实际不太理想，可以使用 [vuepress-plugin-flowchart](https://flowchart.vuepress.ulivz.com/) 代替。

好的,非常感谢!

**Comment by LdFelix** [comment]
> 首先，vuepress是借助 `markdown-it` 来实现 markdown 的解析的，实现特殊的语法，可以借助插件，具体请点击 [这里](https://v1.vuepress.vuejs.org/zh/guide/markdown.html#%E8%BF%9B%E9%98%B6%E9%85%8D%E7%BD%AE)。
> 
> 其次，我个人尝试过 `mermaid` 语法的插件，实际不太理想，可以使用 [vuepress-plugin-flowchart](https://flowchart.vuepress.ulivz.com/) 代替。

好的,非常感谢!
