### ISSUE TITLE
vssueConfig配置项中配置自己的proxy代理不生效问题

### ISSUE THREAD

**Issue by yakunyue** [recoluan/vuepress-theme-reco#320]
#### What is actually happening?
问题原因：Vssue默认使用cors-anywhere的代理服务解决获取github平台的access-token时的跨域问题，但是cors-anywhere现在已经关闭了这个代理服务。于是我根据vuepress-theme-reco和Vusse的配置指南，想通过在vssueConfig配置项中增加proxy参数配置，指向自己的代理服务。但是配置没有生效，请求还是发给了cors-anywhere，我不知道问题出在Vssue还是vuepress-theme-reco，，，求解答。

#### Other relevant information

- Your OS: Centos7
- Node.js version: v12.16.3
- VuePress version: 1.5.2
- VuePress-theme-reco version: 1.5.2
- Which package manager did you use for the install(npm/cnpm/yarn)?yarn

**Comment by recoluan** [comment]
主题并没有重写 vssue 的配置，所以只要配置了就可以传递给vssue，所以请先同 vssue 确认一下问题原因。
