### ISSUE TITLE
导航栏的文章链接也被显示在了博客列表

### ISSUE THREAD

**Issue by laobg** [recoluan/vuepress-theme-reco#325]
- [ ] I confirm that this is an issue rather than a question.

#### What is actually happening?
导航栏的文章链接也被显示在了博客列表
比如：留言板 关于
之前用的1.5.7版本是正常的

#### Other relevant information

- Your OS: 
- Node.js version: 
- VuePress version: 1.8.0
- VuePress-theme-reco version: 1.6.6-alpha.0
- Which package manager did you use for the install(npm/cnpm/yarn)?npm

**Comment by recoluan** [comment]
主题对列表的展示规则做了改动，对于没有写日期的文章也进行了展示，可以使用 `publish: false` 隐藏。
