### ISSUE TITLE
Cannot read property 'themeConfig' of undefined"

### ISSUE THREAD

**Issue by clark-cui** [recoluan/vuepress-theme-reco#327]
#### What is actually happening?
I update vuepress and vuepress-theme-reco,then error.
```
error Error rendering /404.html: false
undefined
[Vue warn]: Error in render: "TypeError: Cannot read property 'themeConfig' of 
undefined"
```

In my reposity,run ``` yarn run build  ``` , It did work.Then i want to update devdependencies.
So i run
 ``` 
     yarn add vuepress-theme-reco vuepress -D
     yarn run build
```
Then error

[**clone my reposity**](https://github.com/clark-cui/blog-clark-cui)
run these scripts,you can find the same problem.

#### Other relevant information

- Your OS: windows10
- Node.js version: 14.16.0
- VuePress version: 1.8.0---1.8.2
- VuePress-theme-reco version: 1.6.1 ---1.6.5
- Which package manager did you use for the install(npm/cnpm/yarn)? yarn

**Comment by laobg** [comment]
[#315](https://github.com/vuepress-reco/vuepress-theme-reco/issues/315)
