### ISSUE TITLE
本地运行正常 服务器克隆下来 npm install 报错 报没有权限

### ISSUE THREAD

**Issue by limingzhi70729697** [recoluan/vuepress-theme-reco#329]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-demi@0.5.4 postinstall: `node ./scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-demi@0.5.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by limingzhi70729697** [comment]
您的操作系统：CentOS  7.2 64位
Node.js版本：v14.10.1
VuePress版本：1.7.1
VuePress-theme-reco版本：1.6.1

**Comment by limingzhi70729697** [comment]
gitee仓库地址： https://gitee.com/xiaomings_gitee/vuepress-theme-reco-my-blog.git

**Comment by recoluan** [comment]
`npm install` 没有权限，就是你的电脑设置的问题了，google 或者 baidu 一下吧。
