### ISSUE TITLE
使用默认主题的Badge组件在部署后出现样式丢失的现象

### ISSUE THREAD

**Issue by ruan-cat** [recoluan/vuepress-theme-reco#398]
# 使用方式
按照文档说明，可以直接使用默认主题提供的Badge组件，使用方式如下：

``` markdown
### 引用类型 <Badge text="进阶"/>
```

在打包并部署到服务器时，出现了样式丢失问题。样式未能够生效。

并未配置其他的内容，只是直接使用了该组件。

目前我正在维护两个个人网站，针对**Badge**组件，两个个人网站的显示效果是不统一的。一个样式显示正常，另一个样式丢失。

## 样式正常的效果
![](https://gitee.com/HechiCollegeComputerAssociation/image-store/raw/master/20220220/@yqpTlhEF*!8.png)

## 样式丢失的效果
![](https://gitee.com/HechiCollegeComputerAssociation/image-store/raw/master/20220220/aBp7)

**Comment by recoluan** [comment]
图片不展示了

**Comment by RuanZhongNan** [comment]
图片已更新，部署后的效果如上图。

**Comment by RuanZhongNan** [comment]
**样式正常**的与**样式丢失**的版本号，均为```"vuepress-theme-reco": "^1.6.10"```。

**Comment by Eastboat** [comment]
> 

请问你的markdown侧边标题导航用的是什么，谢谢

**Comment by RuanZhongNan** [comment]
关于**左侧**和**右侧**的侧边栏，我使用的是`VuePress`插件`vuepress-plugin-auto-sidebar`。

- 左侧边栏
`reco`主题的左侧边栏显示的是文件夹的文件名，我这里的并没有做其他的配置。使用`reco`自动生成的左侧边栏。

- 右侧边栏
使用的是`VuePress`插件[`vuepress-plugin-auto-sidebar`](https://github.com/shanyuhai123/vuepress-plugin-auto-sidebar)。配合`config.js`的`themeConfig`实现右侧边栏的自动生成。

插件是这样使用的：
```js
["vuepress-plugin-auto-sidebar", true, {
  title: {
    mode: "titlecase"
  },

  collapse: {
    open: true
  },

  sidebarDepth: 3,

  // 侧边栏插件 使用自定义排序
  sort: {
    mode: 'custom',
    fn: sortFn
  }
}]
```

`themeConfig`关于侧边栏的配置是这样的：
``` js
themeConfig : {
  sidebar: 'auto',
  subSidebar: 'auto',
  sidebarDepth: 3,
}
```

**Comment by Eastboat** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by recoluan** [comment]
@RuanZhongNan 该问题多与缓存有关，清除一下 node_modules 试一下吧，因为你的两个项目环境是完全相同的，我不太好判断问题的原因，暂时先关闭该 issue 了
