### ISSUE TITLE
请问下文章需要写在那个目录

### ISSUE THREAD

**Issue by guestccc** [recoluan/vuepress-theme-reco#6]
## 首先文中提到分类的步骤

1. 在config中配置目录

2. 新建目录文件两个，一个是前端，一个是后端

3. 写文章时添加分类

> ok，那这个文章是该写在哪个文件夹下，才会被有序渲染在对应的分类里面?

**Comment by guestccc** [comment]
不好意思，真心喜欢您的这个主题，然后试了您说的这些，还是不行
![image](https://user-images.githubusercontent.com/36983617/51307008-971aed00-1a79-11e9-8db8-71a840730d28.png)
![image](https://user-images.githubusercontent.com/36983617/51307069-b87bd900-1a79-11e9-9d18-98133ad2f632.png)
可以麻烦你看看我的配置是否有错么？
麻烦了

**Comment by recoluan** [comment]
我看到你的vue.md的分类是 `backEnd`，但是你的访问的是 `frontEnd`，你试一下访问`backEnd`，看看是不是因为这个吗？
