### ISSUE TITLE
您好，我根据您的文档进行配置，但是在页面没有分类文章

### ISSUE THREAD

**Issue by kangxukangxu** [recoluan/vuepress-theme-reco#7]
![image](https://user-images.githubusercontent.com/17905150/51434971-06762400-1ca8-11e9-946e-e4865f599501.png)
![image](https://user-images.githubusercontent.com/17905150/51434977-0fff8c00-1ca8-11e9-9b82-8641b981f2b3.png)

以上是我这边的配置，但是没有分类下的文章没有检测出来

**Comment by recoluan** [comment]
你好，你的文章里的categories的值是 “frontEnd”，但是分类文件里的title的值是“前段”，这两个值此需要一致才可以。这里可能是我写的还不够详细，后期我完善一下文档。

**Comment by kangxukangxu** [comment]
@recoluan  您好，根据您的说法，已经处理了，还有一个问题，
![image](https://user-images.githubusercontent.com/17905150/51435214-aa160300-1cad-11e9-9120-ee80eb561080.png)
这样的样式怎么出来了，我这边在markdown中写了Tip，但是最终这个列表中没有显示出来
![image](https://user-images.githubusercontent.com/17905150/51435221-c87bfe80-1cad-11e9-8907-236c5caa0129.png)
![image](https://user-images.githubusercontent.com/17905150/51435224-d2056680-1cad-11e9-98c9-b6df2c42323c.png)

请教一下，怎么处理？？？？

**Comment by recoluan** [comment]
文章中可以添加一个注释代码<!— more —>，注释代码前面的文章内容会被放在列表页的文章导引的那个地方。

**Comment by kangxukangxu** [comment]
@recoluan   可以给个栗子吗  对这块还是不太明白

**Comment by recoluan** [comment]
好的，你可以把问题列出来吗？或者加我的微信LHW19930105

**Comment by kangxukangxu** [comment]
好的，微信请求已经发出。



1454900516@qq.com
 
发件人： reco_luan
发送时间： 2019-01-23 10:01
收件人： recoluan/vuepress-theme-reco
抄送： kangxu-nigel; Author
主题： Re: [recoluan/vuepress-theme-reco] 您好，我根据您的文档进行配置，但是在页面没有分类文章 (#7)
好的，你可以把问题列出来吗？或者加我的微信LHW19930105
